---
title: "Rparallelism"
author: "gc5k"
date: "2/19/2020"
output:
  html_document:
    theme: united
    highlight: tango
---
# Rparallelism {.tabset .tabset-fade .tabset-pills}

[See this original blog](https://privefl.github.io/blog/a-guide-to-parallelism-in-r/)

## foreach library
```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
library(foreach)

```

## foreach
```{r foreach}

foreach(i = 1:3) %do% {
  sqrt(i)
}

lapply(1:3, function(i) {
  sqrt(i)
})

foreach(i = 1:3, .combine = 'c') %do% {
  sqrt(i)
}

res <- lapply(1:3, function(i) {
  sqrt(i)
})
do.call('c', res)
```

## Using clusters

```{r cluster}
# Example registering clusters
cl <- parallel::makeCluster(2)
doParallel::registerDoParallel(cl)
foreach(i = 1:3, .combine = 'c') %dopar% {
  sqrt(i)
}
parallel::stopCluster(cl)
```

## bigstatsr lib
```{r bigstatsr}
library(bigstatsr)
mat3 <- FBM(5, 8)
cl <- parallel::makeCluster(2)
doParallel::registerDoParallel(cl)
tmp3 <- foreach(j = 1:8, .combine = 'c') %:%
  foreach(i = 1:5, .combine = 'c') %dopar% {
    mat3[i, j] <- i + j
    NULL
  }
parallel::stopCluster(cl)
mat3[]
```

## bigstatsr::FBM
```{r FBM}
mat <- matrix(0, 1e4, 1e4); mat[] <- rnorm(length(mat))
cl <- parallel::makeCluster(2)
doParallel::registerDoParallel(cl)
system.time(
  tmp <- foreach(k = 1:2, .combine = 'c') %dopar% {
    Sys.sleep(1)
    mat[1, 1]
  }
)
parallel::stopCluster(cl)

mat2 <- FBM(1e4, 1e4); mat2[] <- rnorm(length(mat2))
cl <- parallel::makeCluster(2)
doParallel::registerDoParallel(cl)
system.time(
  tmp <- foreach(k = 1:2, .combine = 'c') %dopar% {
    Sys.sleep(1)
    mat2[1, 1]
  }
)
parallel::stopCluster(cl)
```

## File lock

So each process uses some lock to perform its incrementation so that the data can???t be changed by some other process in the meantime.

```{r flock}
library(flock)
lock <- tempfile()
mat2 <- FBM(1, 1, init = 0)
mat2[]
cl <- parallel::makeCluster(2)
doParallel::registerDoParallel(cl)
foreach(k = 1:10, .combine = 'c') %dopar% {
  locked <- flock::lock(lock)
  mat2[1, 1] <- mat2[1, 1] + k
  flock::unlock(locked)
  NULL
}
```

## cores to use
```{r}
parallel::detectCores()
bigstatsr::nb_cores()
```

