---
title: "ALS"
author: "Chen Guo-Bo [chenguobo@gmail.com]"
date: "`r Sys.Date()`"
output:
 html_document:
    theme: united
    highlight: tango
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(pROC)
library("knitr")
library("kableExtra")

dat=read.csv("20200818all.csv", as.is = T, header = T)

```

# Table of contents {.tabset .tabset-fade .tabset-pills}

## Quality check
```{r, data-check}

par(las=2, font=5, bty='l', ps=6)
boxplot(dat[,-2], cex=0.5, pch=16, col=runif(nrow(dat), 1, nrow(dat)))

##basic accessment of the data
###fivenum, mean, sd, missing, isNumeric
cutoff=7 #outlier pickup

SUMmat=matrix(0, ncol(dat), 10)
colnames(SUMmat)=c("minimum", "lower-hinge", "median", "upper-hinge", "maximum", "mean", "sd", "missingRate", "isNumeric", "CaseOnly")
rownames(SUMmat)=colnames(dat)
for(i in 1:nrow(SUMmat)) {
  if(is.numeric(dat[,i])) {
    SUMmat[i,1:5]=fivenum(dat[,i])
    SUMmat[i,6]=mean(dat[,i], na.rm = T)
    SUMmat[i,7]=sd(dat[,i], na.rm = T)
    naIdx=which(!is.na(dat[,i]))
    SUMmat[i,8]=1-length(naIdx)/nrow(dat)
    SUMmat[i,9]=T
    SUMmat[i,10]=ifelse(length(unique(dat[naIdx,1]))==1, T, F)

    idx=which(dat[,i] > SUMmat[i,6]+cutoff*SUMmat[i,7])
    if(length(idx)>0) {
      for(j in 1:length(idx)) {
        print(paste0("sample id: ",dat[idx[j],2], ", col:", colnames(dat)[i], ", ", "outlier value: ",  dat[idx[j], i]))
      }

    }
  } else {
    SUMmat[i,1:8]=NA
    SUMmat[i,9]=F
  }
}

write.table(SUMmat, "Als_sumDat.txt", row.names = T, col.names = T, quote = F)



basicSum=read.table("Als_sumDat.txt", as.is = T, header = T)
knitr::kable(basicSum, caption = "Data quality") %>%
kable_styling("striped", full_width = T)
#row_spec(row=16:16, color="white", background="red")

```

## Feature selection
```{r, data-p}
Smat=matrix(0, ncol(dat)-2, 4)

for(i in 3:ncol(dat)) {
  mod=glm(dat[,1]~dat[,i], family = "binomial")
  Smat[i-2,]=summary(mod)$coefficients[2,]
}
rownames(Smat)=colnames(dat)[3:ncol(dat)]


aucMat=matrix(2, ncol(dat)-2, 1)
rownames(aucMat)=colnames(dat)[3:ncol(dat)]
for(i in 3:ncol(dat)) {
  if(!SUMmat[colnames(dat)[i],10]) {
    rocObj=roc(dat[,1], dat[,i], quiet = T)
    aucMat[i-2,1]=rocObj$auc
  }
}

layout(matrix(c(1, 2, 3, 4), 2, 2, byrow = F))
par(las=2, cex=0.5, mai=c(1,0.5,0.5,0.5))
pcut=-log10(0.05/(ncol(dat)-2))
barplot(main="case-control",-log10(Smat[,4]), col=ifelse(-log10(Smat[,4])>pcut, "cyan", "grey"))
abline(h=-log10(0.05/ncol(dat)), col="red", lty=2)

barplot(main="case-control", aucMat, beside = T, col=ifelse(-log10(Smat[,4])>pcut, "cyan", "grey"))
plot(-log10(Smat[,4]), pch=16,aucMat,col=ifelse(-log10(Smat[,4])>pcut, "cyan", "grey"))
abline(v=pcut, col="red", lty=2)

###########
SVCmat=matrix(1, ncol(dat)-2, 4)
for(i in 3:ncol(dat)) {
  if(i!=68) {
    mod=lm(dat[,68]~dat[,i])
    if(nrow(summary(mod)$coefficients)>1) {
      SVCmat[i-2,]=summary(mod)$coefficients[2,]
    }
  }
}
rownames(SVCmat)=colnames(dat)[3:ncol(dat)]

par(las=2, cex=0.5, mai=c(1.5,0.5,0.5,0.5))
pcut=-log10(0.05/(ncol(dat)-2))
barplot(-log10(Smat[,4]), col=ifelse(-log10(Smat[,4])>pcut, "cyan", "grey"))
abline(h=-log10(0.05/ncol(dat)), col="red")

```

